site_name: Terraform at Ping Identity
repo_name: pingidentity/terraform-docs
repo_url: https://github.com/pingidentity/terraform-docs
site_url: https://terraform.pingidentity.com/
copyright: © Copyright 2024 Ping Identity
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant
    - navigation.top
    - content.code.annotate
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      accent: blue
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      accent: blue
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.snippets
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

plugins:
  - redirects:
      redirect_maps:
        'best-practices/index.md': 'https://developer.pingidentity.com/terraform/best_practices.html'
        'best-practices/pingone/index.md': 'https://developer.pingidentity.com/terraform/products/pingone/best_practices.html'
        'examples/pingone/configuring-the-pingone-self-service-application.md': 'https://developer.pingidentity.com/terraform/products/pingone/tutorials/configuring_the_self_service_application.html'
        'examples/pingone/role-assignment.md': 'https://developer.pingidentity.com/terraform/products/pingone/tutorials/role_assignment.html'
        'faq/pingdirectory.md': 'https://developer.pingidentity.com/terraform/products/pingdirectory/faq.html'
        'faq/pingfederate.md': 'https://developer.pingidentity.com/terraform/products/pingfederate/faq.html'
        'faq/pingone.md': 'https://developer.pingidentity.com/terraform/products/pingone/faq.html'
        'getting-started/configuration-promotion.md': 'https://developer.pingidentity.com/config-automation-promotion/concepts/overview.html'
        'getting-started/pingdirectory.md': 'https://developer.pingidentity.com/terraform/products/pingdirectory/getting_started.html'
        'getting-started/pingfederate.md': 'https://developer.pingidentity.com/terraform/products/pingfederate/getting_started.html'
        'getting-started/pingone.md': 'https://developer.pingidentity.com/terraform/products/pingone/getting_started.html'
        'index.md': 'https://developer.pingidentity.com/terraform'

nav:
  - Welcome:
      - Home: "index.md"
      - Getting Started:
          - PingOne Provider: "getting-started/pingone.md"
          - DaVinci Provider: "getting-started/davinci.md"
          - PingDirectory Provider: "getting-started/pingdirectory.md"
          - PingFederate Provider: "getting-started/pingfederate.md"
          - Configuration Promotion: "getting-started/configuration-promotion.md"
  - Best Practices:
      - Writing Terraform HCL: "best-practices/index.md"
      - PingOne: "best-practices/pingone/index.md"
      - DaVinci: "best-practices/davinci/index.md"
  - Examples:
      - Home: "examples/index.md"
      - PingOne:
         - Role Permission Assignment: "examples/pingone/role-assignment.md"
  #     - Introduction: "use-case-examples/introduction.md"
  #     - Integrated Solutions:
  #         - PingOne/DaVinci Flow Integration: "use-case-examples/integrated-pingone-davinci-flow.md"
  #         - PingOne Workforce with Windows Login Passwordless: "use-case-examples/integrated-pingone-workforce-windows-login.md"
  - FAQ:
      - PingOne Provider: "faq/pingone.md"
      - DaVinci Provider: "faq/davinci.md"
      - PingDirectory Provider: "faq/pingdirectory.md"
      - PingFederate Provider: "faq/pingfederate.md"
